### ISSUE TITLE
Other team's clues on eye spaces are hidden

### ISSUE THREAD

**Issue by Ramenhotep** [Oliver-Akins/Ghost-Writer-Online#103]
The first 3 or so characters of the other team's eye spaces are hidden behind the eye, which is a bit of a problem. I can think of lots of fixes for this, but an easy one would be making the padding-left of the other team's input fields 30px. (This pushes the center line a bit off center, but it's worth it if there isn't another easy solution)

**Comment by Ramenhotep** [comment]
Update: our temporary fix is literally just putting spaces in front of the clue

**Comment by Oliver-Akins** [comment]
This has been fixed and can be pulled whenever you want it to be
